<a href="https://colab.research.google.com/github/CodeWith-Sana/Learn-ML-WithSana/blob/main/dataPreprocessesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


to make dataset use make_classification

In [14]:
# data  = make_classification(n_samples = 5 , n_features = 2 , n_redundant = 0 , n_classes= 2)

to generate same samples use random_state

In [27]:
data  = make_classification(n_samples = 10 , n_features = 2 , n_redundant = 0 , n_classes= 2 , random_state = 2)

In [4]:
type(data)

tuple

In [28]:
data

(array([[ 1.19233761,  1.68984837],
        [ 2.10468347,  0.08822   ],
        [ 1.04115518, -1.91602762],
        [ 0.28432141, -0.11450983],
        [-0.67458929, -0.89813178],
        [ 0.97869965, -0.57896825],
        [-1.30136943,  0.79786149],
        [ 1.17062352,  0.99746752],
        [-0.12196157, -2.58441629],
        [-0.98692549,  0.68339532]]),
 array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0]))

In [8]:
len(data)

2

In [29]:
X =  data[0]

X features

In [32]:
X

array([[ 1.19233761,  1.68984837],
       [ 2.10468347,  0.08822   ],
       [ 1.04115518, -1.91602762],
       [ 0.28432141, -0.11450983],
       [-0.67458929, -0.89813178],
       [ 0.97869965, -0.57896825],
       [-1.30136943,  0.79786149],
       [ 1.17062352,  0.99746752],
       [-0.12196157, -2.58441629],
       [-0.98692549,  0.68339532]])

In [30]:
Y = data[1]

Y Label/Targets

In [31]:
Y

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [13]:
type(Y)

numpy.ndarray

#data splitting

In [33]:
X_train , X_test , y_train , y_test = train_test_split(X, Y , test_size = 0.2 , random_state = 42)

In [34]:
X_train.shape

(8, 2)

In [43]:
X_train

array([[ 0.97869965, -0.57896825],
       [ 1.19233761,  1.68984837],
       [ 1.17062352,  0.99746752],
       [ 1.04115518, -1.91602762],
       [-0.98692549,  0.68339532],
       [-0.67458929, -0.89813178],
       [ 0.28432141, -0.11450983],
       [-1.30136943,  0.79786149]])

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
Sc = MinMaxScaler()

In [38]:
#help(MinMaxScaler)

In [40]:
Sc.fit(X_train)

MinMaxScaler()

In [41]:
X_train_scaled = Sc.transform(X_train)

In [42]:
X_train_scaled

array([[0.91432917, 0.37080015],
       [1.        , 1.        ],
       [0.99129244, 0.8079854 ],
       [0.93937442, 0.        ],
       [0.12609498, 0.72088529],
       [0.25134474, 0.28228809],
       [0.63587695, 0.49960614],
       [0.        , 0.75262963]])

In [44]:
X_train_scaled.max()

np.float64(1.0)

In [45]:
X_train_scaled.min()

np.float64(0.0)

In [46]:
X_train_scaled_2 = Sc.fit_transform(X_train)

In [47]:
X_train_scaled_2

array([[0.91432917, 0.37080015],
       [1.        , 1.        ],
       [0.99129244, 0.8079854 ],
       [0.93937442, 0.        ],
       [0.12609498, 0.72088529],
       [0.25134474, 0.28228809],
       [0.63587695, 0.49960614],
       [0.        , 0.75262963]])

In [48]:
X_test_scaled = Sc.transform(X_test)

In [50]:
X_test_scaled

array([[ 0.47295365, -0.18536097],
       [ 1.36585928,  0.55582822]])

to perform MinMax scaling in range of -1 and 1

In [51]:
sc = MinMaxScaler(feature_range  =(-1 , 1))

In [52]:
x_train_scaled = sc.fit_transform(X_train)

In [53]:
x_train_scaled.max()

np.float64(1.0)

In [54]:
x_train_scaled.min()

np.float64(-1.0)

## data Standardization

In [56]:
x1 = np.array([1,2,3,4,5,6,7,8,9])

In [57]:
x2 = np.array([10,20,30,40,50,60,70,80,90])
x3 = np.array([100,200,300,400,500,600,700,800,900])

to convert into 2d array use reshape(-1,1)

In [58]:
x1 = x1.reshape(-1,1)
x2 = x2.reshape(-1,1)
x3 = x3.reshape(-1,1)

In [59]:
#to stack all coulmns in one array
x = np.hstack((x1,x2,x3))

In [60]:
x

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500],
       [  6,  60, 600],
       [  7,  70, 700],
       [  8,  80, 800],
       [  9,  90, 900]])

In [61]:
y = np.array([1,2,3,4,5,6,7,8,9])

Splitting the Data


In [62]:
x_train, x_test , y_train , y_test =  train_test_split(x , y , test_size =0.2 , random_state=42)

### Data Standardization

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
sc1 = StandardScaler()

In [65]:
x_train_scaled_1 = sc1.fit_transform(x_train)

In [66]:
x_train_scaled_1

array([[ 0.40824829,  0.40824829,  0.40824829],
       [-1.63299316, -1.63299316, -1.63299316],
       [ 1.63299316,  1.63299316,  1.63299316],
       [-0.81649658, -0.81649658, -0.81649658],
       [ 0.        ,  0.        ,  0.        ],
       [-0.40824829, -0.40824829, -0.40824829],
       [ 0.81649658,  0.81649658,  0.81649658]])

In [67]:
x_train_scaled_1.mean()

np.float64(-2.114710523095536e-17)

In [68]:
x_train_scaled_1.std()

np.float64(1.0)

In [69]:
x_test_scaled1 =sc1.transform(x_test)

In [70]:
x_test_scaled1

array([[ 1.22474487,  1.22474487,  1.22474487],
       [-1.22474487, -1.22474487, -1.22474487]])